### ISSUE TITLE
Redirection should be W3C compliant, not a JS trick

### ISSUE THREAD

**Issue by tstebut** [Vidhyabujju/URLShortener#2]
Actually you could have 2 ways:

One is to use a html meta to perform such redirection, like in this tutorial: https://www.tutorialspoint.com/How-to-redirect-from-an-HTML-page

The other would be to add a rest servie with a 301 return code, which does actually the redirection itself...in terms of API, this could be neat...

Yet I'd prefer 1st way for the beginning, which tend to be really in phase with standards..
2nd way could be added as an option on a second hand though

**Comment by Vidhyabujju** [comment]
Your options are good.... but unfortunately technical blockages are there...
1. Meta tag - possibilities to hanle dynamic data issues. I am researching on it, if you can help me please let me know

2. 301 return, true it should be neat, but when i redirect between pages within my server - for situations like permanent replacement of current url. The redirection am doing is just minification.

**Comment by tstebut** [comment]
> Meta tag - possibilities to hanle dynamic data issues. I am researching on it, if you can help me please let me know

Fine, you hit the spot of lackness 💯 

> 301 return, true it should be neat, but when i redirect between pages within my server - for situations like permanent replacement of current url. The redirection am doing is just minification.

Actually the idea is to use HTTP header arguments into the response of a NEW (optional) rest GET service of your API. Let's start from a copy cat of your minifying service.
So thanks to those arguments, along with a 301 return code, any browser would redirect to the url given (maybe in one header arg, but you gotta dig into it....).
Though , the HTML redirection page would be useless.

=> have fun with restful API protocol tuning

**Comment by Vidhyabujju** [comment]
redirect i have used directly. It works, thank you again.

**Comment by tstebut** [comment]
Actually, after having seen the way you did it I think it is a good start, yet not exactly what was meant.
Not to say it is crucial for a devops to do it right now, however it would be neat to get this on a more Http-protocol-friendly way.

I say it again... If you dig a bit on restful api and http protlcol you might figure out how to trigger the redirection directly from tha api call, without need of another html for redirection. 
To give a clue, you would have to put some args in the http response header, in combination with a 301 return code ;)

Challenged?

**Comment by Vidhyabujju** [comment]
You already challenged and it is already done with redirection, No more html, the redirect html is already out of the code. May be you are confused, since the history of changes are not seen in the master branch. Like you have suggested, i will create 2 branches soon to show the difference clearly.
