### ISSUE TITLE
Suggestion, use a standard urlEncoder instead of reinventing logic here

### ISSUE THREAD

**Issue by tstebut** [Vidhyabujju/URLShortener#3]
https://github.com/Vidhyabujju/URLShortener/blob/f36d5ac9c0f7b20b558c24ac7b68db76b712aa9b/restAPI.py#L102

I'm not a Python expert, yet I'd recommand using an existing library, like e.g. https://www.urlencoder.io/python/

**Comment by Vidhyabujju** [comment]
No one is called expert or perfect in this world.....
True urlencoder can be used but my code doe not need it. 
Google search urls have many , and & in thier url, when you recieve such urls as args, only first part of the url is recieved by flask (please to read abt args and its syntax)
To handle all of this, i have not used quote and unquote option of urlencoder.

**Comment by tstebut** [comment]
> Google search urls have many , and & in thier url, when you recieve such urls as args, only first part of the url is recieved by flask (please to read abt args and its syntax)
> To handle all of this, i have not used quote and unquote option of urlencoder.

This is a bit naive, actually ,as you seem to have only test with google search urls.... but what about any other kind of exceptions ? Tere are plenty , be sure of it, like so many urls to shorten which could contain any other specific character, requiring another replacement....

That's why I insist :=> to keep open the need to take a look at a lib like the one I sugested ;)

**Comment by Vidhyabujju** [comment]
I just checked if urlencoder be used for string (with protocol) and it does, i agree, i will include it. thank you.

**Comment by Vidhyabujju** [comment]
This is included. Thank you.
