### ISSUE TITLE
These logs might not be accurate

### ISSUE THREAD

**Issue by tstebut** [Vidhyabujju/URLShortener#4]
https://github.com/Vidhyabujju/URLShortener/blob/f36d5ac9c0f7b20b558c24ac7b68db76b712aa9b/restAPI.py#L128

https://github.com/Vidhyabujju/URLShortener/blob/f36d5ac9c0f7b20b558c24ac7b68db76b712aa9b/restAPI.py#L117

**Comment by Vidhyabujju** [comment]
Yes, i will modify the logs as new html files are included, i have to make modifications.
Thanks for this micro review
