### ISSUE TITLE
Global advices

### ISSUE THREAD

**Issue by tstebut** [Vidhyabujju/URLShortener#6]
https://github.com/Vidhyabujju/URLShortener/blob/f36d5ac9c0f7b20b558c24ac7b68db76b712aa9b/restAPI.py#L1

- => Remove all unnecessary comments
- => add meaningful comments to describe each important line of code
- => document each class and fuctions
- => Indent everything perfectly

**Comment by Vidhyabujju** [comment]
1. Commented lines are left for purpose, am working on statistics page for this project.
2. ok
3. ok
4. Indentation is good, else python will not even run the application. But i will indent the html files good yes.

**Comment by tstebut** [comment]
good
